### ISSUE TITLE
Missing _css-overrides.less file causing compilation error

### ISSUE THREAD

**Issue by smross** [JoshuaMaiorino/RockTheme-Agency#1]
I installed the theme on my sandbox server, and am experiencing a comilation error.

Steps to reproduce:

1. Install plug-in
2. Configure a site to use the theme
3. Compile theme for the site

Expected behavior:
Theme compiles

Actual behavior:
`Warning: An error occured compiling the theme Agency. Message: You are importing a file ending in .less that cannot be found [_css-overrides.less.]..`

Of note:
the file `_css-overrides.less` does not exist in the styles directory for the theme. If I copy the file from the stark theme, the theme will then compile. However, I'm not sure what that file is used for, so I may be breaking something by doing it this way ;)

I tested this on Rock v7.3
@mikejed also confirmed the problem is repeatable using the demo site

**Comment by JoshuaMaiorino** [comment]
So I downloaded the package from the Rock site, and the file is in the package file I'm downloading.  So I'm not sure why it's not getting placed into the directory.

This file is what's used to override CSS or add custom classes to a theme.  So by default its a blank file.  And on the demo site, it appears as though it was actually compiling despite the error.

Let me see what I can do.  Maybe something happened in the upload/review process.
